### ISSUE TITLE
Re-Enable Dask, add Modin and Dask on Ray

### ISSUE THREAD

**Issue by sullivancolin** [EthanRosenthal/medium-data-bakeoff#12]
This project is great!

I was able to get the dask version to run relatively well by making a small tweak to the way the data is read in.  But that might violate the spirit of your bakeoff.

I changed:
```python
df = dd.read_parquet(dataset, index=False)
```
to
```python
df = dd.read_parquet(dataset, index=False, columns=["station_id", "num_bikes_available"])
```
This allows dask to only read in the columns needed for the groupby().mean() and run much quicker.  But again, that's probably not obvious to typical pandas users and therefore maybe a bit of a cheat.

I also added [modin](https://modin.readthedocs.io/en/latest/index.html) and [dask on ray](https://docs.ray.io/en/latest/data/dask-on-ray.html) as experiments.  I can submit a PR if you would like these to be included.  I have not yet tried [modin in dask](https://modin.readthedocs.io/en/latest/getting_started/using_modin/using_modin_locally.html#optional-configurations).

Here is the rough benchmark I ended up with:

![benchmark_50](https://user-images.githubusercontent.com/10760217/202028062-d6cadb37-2f38-4364-8d4d-26a56636dde5.png)

Let me know your feedback!

**Comment by EthanRosenthal** [comment]
Awesome!

I do agree that the dask optimization maaaayyyy be a bit cheating. That said, I do like being able to once again see its performance on the plot. I'll add it in and add it into the bakeoff but mark it as `dask*` with an explanation in the readme about this cheat.

In terms of modin and dask on ray, a PR would be very welcome! I tried messing around with modin on ray last night but ran into some issues running it on my machine. We'll see if this is a "my machine" thing or if your implementation fixes my issues.
